### ISSUE TITLE
Not built on Alpine Linux

### ISSUE THREAD

**Issue by willthames** [proemergotech/nginx-rtmp-opentracing#4]
This repo is the top hit for nginx opentracing alpine, but it's no longer built on Alpine - you updated the README to reflect that but not the repo description.

I was hoping that it would be possible to get opentracing running on alpine, but perhaps it's just not possible.

**Comment by masterada** [comment]
Thanks for the notice, I updated the description. Nginx jaeger tracing is possible on alpine, we use ubuntu because of the nvidia driver (for ffmpeg gpu support). You can check out the [commit](https://github.com/proemergotech/nginx-rtmp-opentracing/tree/369a0536bdd076a70b721fed5287a5a2257d21a1) before the gpu addition.
